# Auto-Generated by URB AI Translator\nimport numpy as np
from numba import jit
@jit(nopython=True)
def mi_estrategia(times, opens, highs, lows, closes, volumes, InpMagicNumber=202310, InpTradeMode=0, InpRiskType=1, InpRiskValue=1.0, InpStopLossPoints=525, InpRiskReward=2.0, InpUseATRDistance=True, InpATRPeriod=14, InpATRMultiplier=0.5, InpFixedDistance=100, InpExpirationCandles=3, InpDirectionFilter=0, InpEMA_Slow=200, InpEMA_Fast=50, InpEMA_SlopeBars=5, InpEnableStackingFilter=True, InpStackingATR=0.5, InpStrengthFilter=0, InpADXPeriod=14, InpPullbackFilter=0, InpRSI_Period=14, InpStoch_K=14, InpStoch_D=3, InpStoch_Slow=3, InpCCI_Period=20, InpWilliams_Period=14, InpStructureTimeframe=0, InpZigZagType=1, InpZZ_Depth=12, InpZZ_Deviation=5, InpZZ_Backstep=3, InpAdaptiveATR=20, InpAdaptiveK=1.5, InpAdaptiveMinBars=3, InpBOSColor=0, InpMinSwingATR=0.5, InpUseStructureFilter=True, InpBlockOppositeDirections=True, InpUseDailyTrendFilter=False, InpUseActivityFilter=False, InpActivityVolumePeriod=20, InpMinActivityRatio=0.6):
    balance = 10000.0
    position = 0 # 0=flat, 1=long, -1=short
    entry_price = 0.0
    atr = np.zeros_like(closes)
    ema_slow = np.zeros_like(closes)
    ema_fast = np.zeros_like(closes)
    adx = np.zeros_like(closes)
    rsi = np.zeros_like(closes)
    stoch = np.zeros_like(closes)
    cci = np.zeros_like(closes)
    williams = np.zeros_like(closes)
    for i in range(100, len(closes)):
        atr[i] = ta.ATR(closes, period=InpATRPeriod)[i]
        ema_slow[i] = ta.EMA(closes, timeperiod=InpEMA_Slow)[i]
        ema_fast[i] = ta.EMA(closes, timeperiod=InpEMA_Fast)[i]
        adx[i] = ta.ADX(closes, timeperiod=InpADXPeriod)[i]
        rsi[i] = ta.RSI(closes, timeperiod=InpRSI_Period)[i]
        stoch[i] = ta.STOCH(closes, timeperiod=InpStoch_K, slowk_period=InpStoch_D, slowk_matype=0, slowd_period=InpStoch_Slow, slowd_matype=0)[i]
        cci[i] = ta.CCI(closes, timeperiod=InpCCI_Period)[i]
        williams[i] = ta.WILLR(closes, timeperiod=InpWilliams_Period)[i]
        
        canBuy = False
        canSell = False
        strengthOk = False
        if InpDirectionFilter == 0:
            canBuy = True
            canSell = True
        elif InpDirectionFilter == 1:
            canBuy = (closes[i] > ema_slow[i])
            canSell = (closes[i] < ema_slow[i])
        elif InpDirectionFilter == 2:
            canBuy = (ta.EMA(closes, timeperiod=InpEMA_SlopeBars)[-1] > 0)
            canSell = (ta.EMA(closes, timeperiod=InpEMA_SlopeBars)[-1] < 0)
        elif InpDirectionFilter == 3:
            canBuy = (ema_fast[i] > ema_slow[i])
            canSell = (ema_fast[i] < ema_slow[i])
        
        if InpStrengthFilter == 0:
            strengthOk = True
        elif InpStrengthFilter == 1:
            strengthOk = (adx[i] > 20)
        elif InpStrengthFilter == 2:
            strengthOk = (adx[i] > 25)
        
        if InpUseStructureFilter:
            structDir = GetStructureDirection(atr, i)
            if structDir == 1:
                canSell = False
            elif structDir == -1:
                canBuy = False
            else:
                canBuy = False
                canSell = False
        
        if InpUseDailyTrendFilter and i >= 200:
            ema_d1 = ta.EMA(closes[:i+1], timeperiod=200)[-1]
            if closes[i] < ema_d1:
                canBuy = False
            if closes[i] > ema_d1:
                canSell = False
        
        if InpUseActivityFilter:
            if not IsMarketActive(volumes, i):
                canBuy = False
                canSell = False
        
        if canBuy and strengthOk:
            lastLow = GetLastZigZagLow(atr, i)
            if lastLow > 0 and (closes[i] > lastLow and closes[i] - lastLow >= atr[i] * InpMinSwingATR):
                entry_price = lastLow - atr[i] * InpATRMultiplier
                sl_price = entry_price - InpStopLossPoints * _Point
                tp_price = entry_price + (InpStopLossPoints * _Point) * InpRiskReward
                if entry_price > SymbolInfoDouble(_Symbol, SYMBOL_ASK):
                    lots = CalculateLotSize(InpStopLossPoints * _Point)
                    if lots > 0:
                        position = 1
                        entry_price = entry_price
                        balance -= lots * SymbolInfoDouble(_Symbol, SYMBOL_ASK)
        
        if canSell and strengthOk:
            lastHigh = GetLastZigZagHigh(atr, i)
            if lastHigh > 0 and (lastHigh > closes[i] and lastHigh - closes[i] >= atr[i] * InpMinSwingATR):
                entry_price = lastHigh + atr[i] * InpATRMultiplier
                sl_price = entry_price + InpStopLossPoints * _Point
                tp_price = entry_price - (InpStopLossPoints * _Point) * InpRiskReward
                if entry_price < SymbolInfoDouble(_Symbol, SYMBOL_BID):
                    lots = CalculateLotSize(InpStopLossPoints * _Point)
                    if lots > 0:
                        position = -1
                        entry_price = entry_price
                        balance += lots * SymbolInfoDouble(_Symbol, SYMBOL_BID)
    
    return float(balance)